apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres14
  template:
    metadata:
      labels:
        app: postgres14
    spec:
      containers:
        - name: postgres14
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: password
            - name: POSTGRES_USER
              value: sysadm1n
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: database
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-postgres
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc